<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/common/bidding.proto

namespace Google\Ads\GoogleAds\V17\Common;

/**
 * View based bidding where user pays per video view.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.common.ManualCpv</code>
 */
class ManualCpv extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Common\Bidding::initOnce();
        parent::__construct($data);
    }
}
