<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/ad_customizer_placeholder_field.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Values for Ad Customizer placeholder fields.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.AdCustomizerPlaceholderFieldEnum</code>
 */
class AdCustomizerPlaceholderFieldEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\AdCustomizerPlaceholderField::initOnce();
        parent::__construct($data);
    }
}
