<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/ad_destination_type.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enumeration of Google Ads destination types.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.AdDestinationTypeEnum</code>
 */
class AdDestinationTypeEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\AdDestinationType::initOnce();
        parent::__construct($data);
    }
}
