<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/ad_serving_optimization_status.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Possible ad serving statuses of a campaign.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.AdServingOptimizationStatusEnum</code>
 */
class AdServingOptimizationStatusEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\AdServingOptimizationStatus::initOnce();
        parent::__construct($data);
    }
}
