<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/advertising_channel_type.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * The channel type a campaign may target to serve on.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.AdvertisingChannelTypeEnum</code>
 */
class AdvertisingChannelTypeEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\AdvertisingChannelType::initOnce();
        parent::__construct($data);
    }
}
