<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/app_bidding_goal.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum describing an app bidding goal for raise Target CPA
 * recommendation.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.AppBiddingGoalEnum</code>
 */
class AppBiddingGoalEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\AppBiddingGoal::initOnce();
        parent::__construct($data);
    }
}
