<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/app_payment_model_type.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Represents a criterion for targeting paid apps.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.AppPaymentModelTypeEnum</code>
 */
class AppPaymentModelTypeEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\AppPaymentModelType::initOnce();
        parent::__construct($data);
    }
}
