<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/attribution_model.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum representing the attribution model that describes how to
 * distribute credit for a particular conversion across potentially many prior
 * interactions.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.AttributionModelEnum</code>
 */
class AttributionModelEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\AttributionModel::initOnce();
        parent::__construct($data);
    }
}
