<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/change_event_resource_type.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum describing supported resource types for the ChangeEvent
 * resource.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.ChangeEventResourceTypeEnum</code>
 */
class ChangeEventResourceTypeEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\ChangeEventResourceType::initOnce();
        parent::__construct($data);
    }
}
