<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/converting_user_prior_engagement_type_and_ltv_bucket.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enumeration of converting user prior engagement types and
 * lifetime-value bucket.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.ConvertingUserPriorEngagementTypeAndLtvBucketEnum</code>
 */
class ConvertingUserPriorEngagementTypeAndLtvBucketEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\ConvertingUserPriorEngagementTypeAndLtvBucket::initOnce();
        parent::__construct($data);
    }
}
