<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/conversion_environment_enum.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum representing the conversion environment an uploaded
 * conversion was recorded on, for example, App or Web.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.ConversionEnvironmentEnum</code>
 */
class ConversionEnvironmentEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\ConversionEnvironmentEnum::initOnce();
        parent::__construct($data);
    }
}
