<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/day_of_week.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enumeration of days of the week, for example, "Monday".
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.DayOfWeekEnum</code>
 */
class DayOfWeekEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\DayOfWeek::initOnce();
        parent::__construct($data);
    }
}
