<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/feed_item_set_string_filter_type.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * The type of string matching to be used for a dynamic FeedItemSet filter.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.FeedItemSetStringFilterTypeEnum</code>
 */
class FeedItemSetStringFilterTypeEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\FeedItemSetStringFilterType::initOnce();
        parent::__construct($data);
    }
}
