<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/geo_targeting_restriction.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Message describing feed item geo targeting restriction.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.GeoTargetingRestrictionEnum</code>
 */
class GeoTargetingRestrictionEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\GeoTargetingRestriction::initOnce();
        parent::__construct($data);
    }
}
