<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/geo_target_constant_status.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for describing the status of a geo target constant.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.GeoTargetConstantStatusEnum</code>
 */
class GeoTargetConstantStatusEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\GeoTargetConstantStatus::initOnce();
        parent::__construct($data);
    }
}
