<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/identity_verification_program.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for IdentityVerificationProgram.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.IdentityVerificationProgramEnum</code>
 */
class IdentityVerificationProgramEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\IdentityVerificationProgram::initOnce();
        parent::__construct($data);
    }
}
