<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/job_placeholder_field.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Values for Job placeholder fields.
 * For more information about dynamic remarketing feeds, see
 * https://support.google.com/google-ads/answer/6053288.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.JobPlaceholderFieldEnum</code>
 */
class JobPlaceholderFieldEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\JobPlaceholderField::initOnce();
        parent::__construct($data);
    }
}
