<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/keyword_plan_forecast_interval.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enumeration of forecast intervals.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.KeywordPlanForecastIntervalEnum</code>
 */
class KeywordPlanForecastIntervalEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\KeywordPlanForecastInterval::initOnce();
        parent::__construct($data);
    }
}
