<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/keyword_plan_keyword_annotation.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enumeration of keyword plan keyword annotations.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.KeywordPlanKeywordAnnotationEnum</code>
 */
class KeywordPlanKeywordAnnotationEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\KeywordPlanKeywordAnnotation::initOnce();
        parent::__construct($data);
    }
}
