<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/local_services_lead_credit_state.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum describing possible credit states of a lead.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.LocalServicesCreditStateEnum</code>
 */
class LocalServicesCreditStateEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\LocalServicesLeadCreditState::initOnce();
        parent::__construct($data);
    }
}
