<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/matching_function_context_type.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for context types for an operand in a matching function.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.MatchingFunctionContextTypeEnum</code>
 */
class MatchingFunctionContextTypeEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\MatchingFunctionContextType::initOnce();
        parent::__construct($data);
    }
}
