<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/month_of_year.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enumeration of months of the year, for example, "January".
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.MonthOfYearEnum</code>
 */
class MonthOfYearEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\MonthOfYear::initOnce();
        parent::__construct($data);
    }
}
