<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/offline_conversion_diagnostic_status_enum.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * All possible statuses for oci diagnostics.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.OfflineConversionDiagnosticStatusEnum</code>
 */
class OfflineConversionDiagnosticStatusEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\OfflineConversionDiagnosticStatusEnum::initOnce();
        parent::__construct($data);
    }
}
