<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/product_issue_severity.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * The severity of a product issue.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.ProductIssueSeverityEnum</code>
 */
class ProductIssueSeverityEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\ProductIssueSeverity::initOnce();
        parent::__construct($data);
    }
}
