<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/product_custom_attribute_index.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum describing the index of the product custom attribute.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.ProductCustomAttributeIndexEnum</code>
 */
class ProductCustomAttributeIndexEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\ProductCustomAttributeIndex::initOnce();
        parent::__construct($data);
    }
}
