<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/reach_plan_surface.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum describing surfaces available for targeting in forecasts.
 * Surfaces refer to the available types of ad inventories such as In-Feed,
 * In-Stream, and Shorts.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.ReachPlanSurfaceEnum</code>
 */
class ReachPlanSurfaceEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\ReachPlanSurface::initOnce();
        parent::__construct($data);
    }
}
