<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/resource_change_operation.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum describing resource change operations
 * in the ChangeEvent resource.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.ResourceChangeOperationEnum</code>
 */
class ResourceChangeOperationEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\ResourceChangeOperation::initOnce();
        parent::__construct($data);
    }
}
