<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/seasonality_event_scope.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Message describing seasonality event scopes. The two types of seasonality
 * events are BiddingSeasonalityAdjustments and BiddingDataExclusions.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.SeasonalityEventScopeEnum</code>
 */
class SeasonalityEventScopeEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\SeasonalityEventScope::initOnce();
        parent::__construct($data);
    }
}
