<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/tracking_code_page_format.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum describing the format of the web page where the tracking
 * tag and snippet will be installed.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.TrackingCodePageFormatEnum</code>
 */
class TrackingCodePageFormatEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\TrackingCodePageFormat::initOnce();
        parent::__construct($data);
    }
}
