<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/user_list_date_rule_item_operator.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Supported rule operator for date type.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.UserListDateRuleItemOperatorEnum</code>
 */
class UserListDateRuleItemOperatorEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\UserListDateRuleItemOperator::initOnce();
        parent::__construct($data);
    }
}
