<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/enums/value_rule_set_dimension.proto

namespace Google\Ads\GoogleAds\V17\Enums;

/**
 * Container for enum describing possible dimensions of a conversion value rule
 * set.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.enums.ValueRuleSetDimensionEnum</code>
 */
class ValueRuleSetDimensionEnum extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Enums\ValueRuleSetDimension::initOnce();
        parent::__construct($data);
    }
}
