<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/resources/recommendation.proto

namespace Google\Ads\GoogleAds\V17\Resources\Recommendation;

/**
 * Recommendation to deploy Google Tag on more pages.
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.resources.Recommendation.ImproveGoogleTagCoverageRecommendation</code>
 */
class ImproveGoogleTagCoverageRecommendation extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Resources\Recommendation::initOnce();
        parent::__construct($data);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ImproveGoogleTagCoverageRecommendation::class, \Google\Ads\GoogleAds\V17\Resources\Recommendation_ImproveGoogleTagCoverageRecommendation::class);
