<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v17/services/customer_service.proto

namespace Google\Ads\GoogleAds\V17\Services;

/**
 * Request message for
 * [CustomerService.ListAccessibleCustomers][google.ads.googleads.v17.services.CustomerService.ListAccessibleCustomers].
 *
 * Generated from protobuf message <code>google.ads.googleads.v17.services.ListAccessibleCustomersRequest</code>
 */
class ListAccessibleCustomersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Google\Ads\GoogleAds\V17\Services\CustomerService::initOnce();
        parent::__construct($data);
    }
}
